-- Local staging only. Copies non-personal reference data (course catalog +
-- statewide deadlines) from the production project so layouts can be built and
-- tested against real content. Not a migration; not applied to any remote env.

insert into canonical_courses (course_name, category) values
  ('English Composition I','English / Writing'),
  ('English Composition II','English / Writing'),
  ('Technical Writing','English / Writing'),
  ('Creative Writing','English / Writing'),
  ('Public Speaking','English / Writing'),
  ('Business Communication','English / Writing'),
  ('College Algebra','Math'),
  ('Precalculus','Math'),
  ('Calculus I','Math'),
  ('Calculus II','Math'),
  ('Calculus III','Math'),
  ('Statistics','Math'),
  ('Business Statistics','Math'),
  ('Linear Algebra','Math'),
  ('Differential Equations','Math'),
  ('Discrete Mathematics','Math'),
  ('Biology I','Science'),
  ('Biology II','Science'),
  ('General Chemistry I','Science'),
  ('General Chemistry II','Science'),
  ('Organic Chemistry I','Science'),
  ('Organic Chemistry II','Science'),
  ('Physics I','Science'),
  ('Physics II','Science'),
  ('Environmental Science','Science'),
  ('Earth Science','Science'),
  ('Geology','Science'),
  ('Astronomy','Science'),
  ('Intro to Programming','Computer Science / Technology'),
  ('Programming Fundamentals','Computer Science / Technology'),
  ('Data Structures','Computer Science / Technology'),
  ('Computer Organization','Computer Science / Technology'),
  ('Discrete Math','Computer Science / Technology'),
  ('Web Development','Computer Science / Technology'),
  ('Database Systems','Computer Science / Technology'),
  ('Cybersecurity Fundamentals','Computer Science / Technology'),
  ('Computer Networks','Computer Science / Technology'),
  ('Software Engineering Fundamentals','Computer Science / Technology'),
  ('Financial Accounting','Business'),
  ('Managerial Accounting','Business'),
  ('Microeconomics','Business'),
  ('Macroeconomics','Business'),
  ('Business Law','Business'),
  ('Business Calculus','Business'),
  ('Principles of Management','Business'),
  ('Marketing Fundamentals','Business'),
  ('Information Systems Fundamentals','Business'),
  ('Engineering Mechanics','Engineering'),
  ('Statics','Engineering'),
  ('Dynamics','Engineering'),
  ('Circuit Analysis','Engineering'),
  ('Engineering Physics','Engineering'),
  ('Engineering Design','Engineering'),
  ('Materials Science','Engineering'),
  ('Thermodynamics','Engineering'),
  ('Intro to Engineering','Engineering'),
  ('Psychology','Social Sciences'),
  ('Sociology','Social Sciences'),
  ('American Government','Social Sciences'),
  ('Texas Government','Social Sciences'),
  ('U.S. History I','Social Sciences'),
  ('U.S. History II','Social Sciences'),
  ('World History','Social Sciences'),
  ('Anthropology','Social Sciences'),
  ('Human Geography','Social Sciences'),
  ('Political Science','Social Sciences'),
  ('Philosophy','Humanities'),
  ('Ethics','Humanities'),
  ('Art Appreciation','Humanities'),
  ('Music Appreciation','Humanities'),
  ('Literature','Humanities'),
  ('Humanities','Humanities'),
  ('Religious Studies','Humanities'),
  ('Anatomy & Physiology I','Health / Pre-Med'),
  ('Anatomy & Physiology II','Health / Pre-Med'),
  ('Microbiology','Health / Pre-Med'),
  ('Nutrition','Health / Pre-Med'),
  ('Kinesiology','Health / Pre-Med'),
  ('Medical Terminology','Health / Pre-Med'),
  ('Health Sciences','Health / Pre-Med'),
  ('Public Health','Health / Pre-Med'),
  ('Intro to Communication','Communication / Media'),
  ('Media Studies','Communication / Media'),
  ('Journalism','Communication / Media'),
  ('Public Relations','Communication / Media'),
  ('Digital Media','Communication / Media'),
  ('Film Studies','Communication / Media'),
  ('Intro to Education','Education'),
  ('Child Development','Education'),
  ('Educational Psychology','Education'),
  ('Special Education Fundamentals','Education'),
  ('Intro to Architecture','Architecture / Design'),
  ('Graphic Design Fundamentals','Architecture / Design'),
  ('Design Principles','Architecture / Design'),
  ('Interior Design Fundamentals','Architecture / Design'),
  ('Animal Science','Agriculture / Environment'),
  ('Plant Science','Agriculture / Environment'),
  ('Agricultural Economics','Agriculture / Environment'),
  ('Environmental Sustainability','Agriculture / Environment'),
  ('Freshman Seminar','General Electives'),
  ('College Success','General Electives'),
  ('Leadership Studies','General Electives'),
  ('Internship/Practicum','General Electives'),
  ('Independent Study','General Electives')
on conflict (course_name) do nothing;

-- Statewide deadlines (university_id null) only, so no FK depends on local
-- university ids matching production.
insert into deadlines (university_id, title, description, due_date, category, academic_term, academic_year, official_info_url) values
  (null,'ApplyTexas transfer application opens','Typical August opening for the new application cycle — confirm on ApplyTexas.','2026-08-01','application',null,null,'https://www.goapplytexas.org/'),
  (null,'FAFSA / TASFA priority date','Use for financial aid planning — confirm federal and institutional deadlines.','2027-01-15','financial_aid',null,null,'https://studentaid.gov/apply-for-aid/fafsa/filling-out'),
  (null,'Fall 2026 Housing Application Opens','On-campus housing applications typically open in spring. Apply early for best selection.','2026-04-01','housing','Fall','2026',null),
  (null,'Fall 2026 Transfer Orientation','Most universities require transfer students to attend orientation before registering for classes.','2026-06-15','registration','Fall','2026',null)
on conflict do nothing;
