-- =============================================================
-- Texas Transfer — School seed data
-- Safe to run multiple times: ON CONFLICT (name) DO NOTHING
-- =============================================================

INSERT INTO public.universities (name, abbreviation, location, type) VALUES

-- ── Community Colleges ──────────────────────────────────────
('Dallas College',                       'DC',      'Dallas, TX',          'community_college'),
('Collin College',                       'Collin',  'McKinney, TX',        'community_college'),
('Austin Community College',             'ACC',     'Austin, TX',          'community_college'),
('Houston Community College',            'HCC',     'Houston, TX',         'community_college'),
('San Jacinto College',                  'SJC',     'Pasadena, TX',        'community_college'),
('Lone Star College',                    'LSC',     'The Woodlands, TX',   'community_college'),
('Tarrant County College',               'TCC',     'Fort Worth, TX',      'community_college'),
('El Paso Community College',            'EPCC',    'El Paso, TX',         'community_college'),
('Alamo Colleges',                       'Alamo',   'San Antonio, TX',     'community_college'),
('McLennan Community College',           'MCC',     'Waco, TX',            'community_college'),
('Temple College',                       'Temple',  'Temple, TX',          'community_college'),
('Blinn College',                        'Blinn',   'Brenham, TX',         'community_college'),
('Kilgore College',                      'Kilgore', 'Kilgore, TX',        'community_college'),
('Tyler Junior College',                 'TJC',     'Tyler, TX',           'community_college'),
('Odessa College',                       'Odessa',  'Odessa, TX',          'community_college'),
('South Texas College',                  'STC',     'McAllen, TX',         'community_college'),
('Del Mar College',                      'DMC',     'Corpus Christi, TX',  'community_college'),
('Coastal Bend College',                 'CBC',     'Beeville, TX',        'community_college'),
('Trinity Valley Community College',     'TVCC',    'Athens, TX',          'community_college'),
('Hill College',                         'Hill',    'Hillsboro, TX',       'community_college'),
('Navarro College',                      'Navarro', 'Corsicana, TX',       'community_college'),
('Paris Junior College',                 'PJC',     'Paris, TX',           'community_college'),
('Northeast Texas Community College',    'NTCC',    'Mount Pleasant, TX',  'community_college'),
('Panola College',                       'Panola',  'Carthage, TX',        'community_college'),
('Lamar Institute of Technology',        'LIT',     'Beaumont, TX',        'community_college'),
('Lamar State College',                  'LSCO',   'Orange, TX',          'community_college'),
('Lee College',                          'Lee',     'Baytown, TX',         'community_college'),
('Galveston College',                    'GC',      'Galveston, TX',       'community_college'),
('Wharton County Junior College',        'WCJC',    'Wharton, TX',         'community_college'),
('Victoria College',                     'VC',      'Victoria, TX',        'community_college'),
('Southwest Texas Junior College',       'SWTJC',   'Uvalde, TX',          'community_college'),

-- ── Four-Year Universities ──────────────────────────────────
('The University of Texas at Austin',    'UT Austin','Austin, TX',         'four_year'),
('Texas A&M University',                 'TAMU',    'College Station, TX', 'four_year'),
('University of Houston',                'UH',      'Houston, TX',         'four_year'),
('Baylor University',                    'BU',      'Waco, TX',            'four_year'),
('Southern Methodist University',        'SMU',     'Dallas, TX',          'four_year'),
('University of Texas at San Antonio',   'UTSA',    'San Antonio, TX',     'four_year'),
('University of Texas at Arlington',     'UTA',     'Arlington, TX',       'four_year'),
('University of Texas at Dallas',        'UTD',     'Richardson, TX',      'four_year'),
('Texas Tech University',                'TTU',     'Lubbock, TX',         'four_year'),
('Texas Christian University',           'TCU',     'Fort Worth, TX',      'four_year'),
('Rice University',                      'Rice',    'Houston, TX',         'four_year'),
('Texas State University',               'TXST',    'San Marcos, TX',      'four_year'),
('University of North Texas',            'UNT',     'Denton, TX',          'four_year'),
('Texas Woman''s University',            'TWU',     'Denton, TX',          'four_year'),
('Sam Houston State University',         'SHSU',    'Huntsville, TX',      'four_year'),
('Stephen F. Austin State University',   'SFA',     'Nacogdoches, TX',     'four_year'),
('Lamar University',                     'Lamar',   'Beaumont, TX',        'four_year'),
('Angelo State University',              'ASU',     'San Angelo, TX',      'four_year'),
('Tarleton State University',            'Tarleton','Stephenville, TX',    'four_year'),
('Texas A&M University-Commerce',        'TAMUC',   'Commerce, TX',        'four_year'),
('Texas A&M University-Corpus Christi',  'TAMUCC',  'Corpus Christi, TX',  'four_year'),
('Texas A&M University-Kingsville',      'TAMUK',   'Kingsville, TX',      'four_year'),
('Prairie View A&M University',          'PVAMU',   'Prairie View, TX',    'four_year'),
('West Texas A&M University',            'WTAMU',   'Canyon, TX',          'four_year'),
('University of Houston-Downtown',       'UHD',     'Houston, TX',         'four_year'),
('University of Houston-Clear Lake',     'UHCL',    'Houston, TX',         'four_year'),
('University of Houston-Victoria',       'UHV',     'Victoria, TX',        'four_year'),
('Texas Southern University',            'TSU',     'Houston, TX',         'four_year'),
('Abilene Christian University',         'ACU',     'Abilene, TX',         'four_year'),
('Hardin-Simmons University',            'HSU',     'Abilene, TX',         'four_year'),
('LeTourneau University',                'LETU',    'Longview, TX',        'four_year'),
('University of Mary Hardin-Baylor',     'UMHB',    'Belton, TX',          'four_year'),
('Texas Lutheran University',            'TLU',     'Seguin, TX',          'four_year'),
('Schreiner University',                 'Schreiner','Kerrville, TX',      'four_year'),
('University of the Incarnate Word',     'UIW',     'San Antonio, TX',     'four_year'),
('St. Mary''s University',               'StMU',    'San Antonio, TX',     'four_year'),
('Trinity University',                   'Trinity', 'San Antonio, TX',     'four_year'),
('Texas A&M International University',   'TAMIU',   'Laredo, TX',          'four_year'),
('Midwestern State University',          'MSU',     'Wichita Falls, TX',   'four_year'),
('Sul Ross State University',            'SRSU',    'Alpine, TX',          'four_year')

ON CONFLICT (name) DO NOTHING;
